version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "02:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    groups:
      npm-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: "/browser"
    schedule:
      interval: daily
      time: "02:10"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 10
    groups:
      npm-minor-patch:
        update-types:
          - minor
          - patch
