const mcl = require('./mcl.js')

mcl.init(mcl.BLS12_381).then(() => {
  console.log('ok')
  mcl.setETHserialization(true)
  mcl.setMapToMode(mcl.IRTF)
  let g1 = new mcl.G1()
  let g2 = new mcl.G2()
  console.log(`g2 zero=${g2.serializeToHexStr()}`)
  g1.setHashOf("asdf")
  g1.normalize()
  console.log(`g1.x=${g1.getX().serializeToHexStr()}`)
  console.log(`g1.y=${g1.getY().serializeToHexStr()}`)
  g2.setHashOf("asdf")
  g2.normalize()
  console.log(`g2.x=${g2.getX().serializeToHexStr()}`)
  console.log(`g2.y=${g2.getY().serializeToHexStr()}`)
})
