import getRandomValues from './getRandomValues'
import { CurveType, MCLBN_COMPILED_TIME_VAR, MCLBN_FP_SIZE, MCLBN_FR_SIZE, MCLBN_G1_SIZE, MCLBN_G2_SIZE, MCLBN_GT_SIZE } from './constants'
import createModule = require('./mcl_c.js')

/** @internal singleton of MCL WASM module generated by emscripten. */
export let mod: any

/** @internal hot-path module-level refs to avoid dictionary-mode lookups on mod */
export let HEAP8: Int8Array
export let HEAP32: Int32Array
export let stackSave: () => number
export let stackAlloc: (n: number) => number
export let stackRestore: (v: number) => void
/** @internal shared wrappers defined in glue.js (see src/mcl/src/wasm/glue.js) */
export let copyToHeap32: (a: Uint32Array, pos: number) => void
export let copyFromHeap32: (a: Uint32Array, pos: number) => void
export let salloc: (a: Uint32Array) => number
export let sallocCopy: (a: Uint32Array) => number
export let sallocBytes: (buf: Uint8Array) => number
export let sallocArray: (arr: Uint32Array[]) => number
export let saveArray: (arr: Uint32Array[], pos: number) => void
export let callSetter: (func: Function, a: Uint32Array, p1?: any, p2?: any) => void
export let callGetter: (func: Function, a: Uint32Array, p1?: any, p2?: any) => any
export let callGetter2: (func: Function, x: Uint32Array, y: Uint32Array, p1?: any) => any
export let callOp1: (func: Function, y: Uint32Array, x: Uint32Array, p1?: any) => any
export let callOp2: (func: Function, z: Uint32Array, x: Uint32Array, y: Uint32Array) => any
export let callShare: (func: Function, y: Uint32Array, vec: Uint32Array[], id: Uint32Array) => any
export let callRecover: (func: Function, y: Uint32Array, idVec: Uint32Array[], vec: Uint32Array[]) => any
export let callSetInput: (func: Function, a: Uint32Array, buf: string | Uint8Array, ioMode?: number) => void
export let callGetStr: (func: Function, a: Uint32Array, ioMode?: number, returnAsStr?: boolean) => any
export let callDeserialize: (func: Function, a: Uint32Array, buf: Uint8Array) => void
export let callSerialize: (func: Function, a: Uint32Array) => Uint8Array
interface MallocDebugState {
  enabled: boolean
  total: number
  ptr: Record<number, number>
  his: Array<[number, number]>
}

export const mallocDebug: MallocDebugState = {
  enabled: false,
  total: 0,
  ptr: {},
  his: []
}

export const getMemory = (): { buffer: ArrayBuffer } => mod.wasmMemory

export const ptrToAsciiStr = (pos: number, n: number): string => {
  let s = ''
  for (let i = 0; i < n; i++) {
    s += String.fromCharCode(mod.HEAP8[pos + i])
  }
  return s
}

export const asciiStrToPtr = (pos: number, s: string): void => {
  for (let i = 0; i < s.length; i++) {
    mod.HEAP8[pos + i] = s.charCodeAt(i)
  }
}

export const toHex = (a: Uint8Array, start: number, n: number): string => {
  let s = ''
  for (let i = 0; i < n; i++) {
    s += ('0' + a[start + i].toString(16)).slice(-2)
  }
  return s
}

// Uint8Array to hex string
export const toHexStr = (a: Uint8Array): string => {
  return toHex(a, 0, a.length)
}

// hex string to Uint8Array
export const fromHexStr = (s: string): Uint8Array => {
  if ((s.length & 1) !== 0) throw new Error(`fromHexStr:length must be even (${s.length})`)
  const n = s.length / 2
  const a = new Uint8Array(n)
  for (let i = 0; i < n; i++) {
    a[i] = parseInt(s.slice(i * 2, i * 2 + 2), 16)
  }
  return a
}

export const free = (x: number): void => {
  mod._free(x)
}

const addWrappedMethods = (): void => {
  mod.mclBnFr_malloc = () => {
    return mod._malloc(MCLBN_FR_SIZE)
  }
  mod.mclBnFr_setLittleEndian = mod.wrapInput(mod._mclBnFr_setLittleEndian, 1)
  mod.mclBnFr_setLittleEndianMod = mod.wrapInput(mod._mclBnFr_setLittleEndianMod, 1)
  mod.mclBnFr_setBigEndianMod = mod.wrapInput(mod._mclBnFr_setBigEndianMod, 1)
  mod.mclBnFr_setStr = mod.wrapInput(mod._mclBnFr_setStr, 1)
  mod.mclBnFr_getStr = mod.wrapGetStr(mod._mclBnFr_getStr)
  mod.mclBnFr_deserialize = mod.wrapDeserialize(mod._mclBnFr_deserialize)
  mod.mclBnFr_serialize = mod.wrapSerialize(mod._mclBnFr_serialize)
  mod.mclBnFr_setHashOf = mod.wrapInput(mod._mclBnFr_setHashOf, 1)
  /// ////////////////////////////////////////////////////////////
  mod.mclBnFp_malloc = () => {
    return mod._malloc(MCLBN_FP_SIZE)
  }
  mod.mclBnFp_setLittleEndian = mod.wrapInput(mod._mclBnFp_setLittleEndian, 1)
  mod.mclBnFp_setLittleEndianMod = mod.wrapInput(mod._mclBnFp_setLittleEndianMod, 1)
  mod.mclBnFp_setBigEndianMod = mod.wrapInput(mod._mclBnFp_setBigEndianMod, 1)
  mod.mclBnFp_setStr = mod.wrapInput(mod._mclBnFp_setStr, 1)
  mod.mclBnFp_getStr = mod.wrapGetStr(mod._mclBnFp_getStr)
  mod.mclBnFp_deserialize = mod.wrapDeserialize(mod._mclBnFp_deserialize)
  mod.mclBnFp_serialize = mod.wrapSerialize(mod._mclBnFp_serialize)
  mod.mclBnFp_setHashOf = mod.wrapInput(mod._mclBnFp_setHashOf, 1)

  mod.mclBnFp2_malloc = () => {
    return mod._malloc(MCLBN_FP_SIZE * 2)
  }
  mod.mclBnFp2_deserialize = mod.wrapDeserialize(mod._mclBnFp2_deserialize)
  mod.mclBnFp2_serialize = mod.wrapSerialize(mod._mclBnFp2_serialize)

  /// ////////////////////////////////////////////////////////////
  mod.mclBnG1_malloc = () => {
    return mod._malloc(MCLBN_G1_SIZE)
  }
  mod.mclBnG1_setStr = mod.wrapInput(mod._mclBnG1_setStr, 1)
  mod.mclBnG1_getStr = mod.wrapGetStr(mod._mclBnG1_getStr)
  mod.mclBnG1_deserialize = mod.wrapDeserialize(mod._mclBnG1_deserialize)
  mod.mclBnG1_serialize = mod.wrapSerialize(mod._mclBnG1_serialize)
  mod.mclBnG1_hashAndMapTo = mod.wrapInput(mod._mclBnG1_hashAndMapTo, 1)

  /// ////////////////////////////////////////////////////////////
  mod.mclBnG2_malloc = () => {
    return mod._malloc(MCLBN_G2_SIZE)
  }
  mod.mclBnG2_setStr = mod.wrapInput(mod._mclBnG2_setStr, 1)
  mod.mclBnG2_getStr = mod.wrapGetStr(mod._mclBnG2_getStr)
  mod.mclBnG2_deserialize = mod.wrapDeserialize(mod._mclBnG2_deserialize)
  mod.mclBnG2_serialize = mod.wrapSerialize(mod._mclBnG2_serialize)
  mod.mclBnG2_hashAndMapTo = mod.wrapInput(mod._mclBnG2_hashAndMapTo, 1)

  /// ////////////////////////////////////////////////////////////
  mod.mclBnGT_malloc = () => {
    return mod._malloc(MCLBN_GT_SIZE)
  }
  mod.mclBnGT_deserialize = mod.wrapDeserialize(mod._mclBnGT_deserialize)
  mod.mclBnGT_serialize = mod.wrapSerialize(mod._mclBnGT_serialize)
  mod.mclBnGT_setStr = mod.wrapInput(mod._mclBnGT_setStr, 1)
  mod.mclBnGT_getStr = mod.wrapGetStr(mod._mclBnGT_getStr)

  /*
    she libray always uses (malloc,free) in nested pairs.
  */
  const mallocOrg: (size: number) => number = mod._malloc
  const freeOrg: (ptr: number) => void = mod._free
  mallocDebug.total = 0
  mod._mallocDebug = (size: number): number => {
    const p = mallocOrg(size + 4)
    HEAP8[p + size] = 0x12
    HEAP8[p + size + 1] = 0x34
    HEAP8[p + size + 2] = 0x56
    HEAP8[p + size + 3] = 0x78
    mallocDebug.his.push([p, size])
    mallocDebug.ptr[p] = size
    mallocDebug.total += size
    return p
  }
  mod._freeDebug = (pos: number): void => {
    const ps = mallocDebug.his.pop() as [number, number]
    const p = ps[0]
    const size = ps[1]
    if (pos !== p) {
      console.log(`pos=${pos} oldPos=${p}`)
    }
    const v = HEAP8[p + size] + (HEAP8[p + size + 1] << 8) + (HEAP8[p + size + 2] << 16) + (HEAP8[p + size + 3] << 24)
    if (v !== 0x78563412) {
      console.log(`ERR=${p} v=${v.toString(16)}`)
    }
    freeOrg(pos)
    const s = mallocDebug.ptr[pos]
    if (s === 0) {
      console.log(`ERR ${pos}`)
    } else {
      // eslint-disable-next-line @typescript-eslint/no-dynamic-delete
      delete mallocDebug.ptr[pos]
      mallocDebug.total -= s
    }
  }
  if (mallocDebug.enabled) {
    mod._malloc = mod._mallocDebug
    mod._free = mod._freeDebug
  }
}

export const _showDebug = (): void => {
  if (mallocDebug.enabled) {
    console.log('malloc DEBUG mode')
    console.log(`  show total=${mallocDebug.total}`)
    console.log(`  g_ptr=${JSON.stringify(mallocDebug.ptr, null, '\t')}`)
  }
}

/** given `CurveType` of last `initializeMcl` call */
export let initializedCurveType: CurveType

export const initializeMcl = async (curveType = CurveType.BN254): Promise<void> => {
  mod = await createModule({
    cryptoGetRandomValues: (a: Uint8Array) => {
      getRandomValues(a)
    }
  })

  HEAP8 = mod.HEAP8
  HEAP32 = mod.HEAP32
  stackSave = mod.stackSave
  stackAlloc = mod.stackAlloc
  stackRestore = mod.stackRestore
  copyToHeap32 = mod.copyToHeap32
  copyFromHeap32 = mod.copyFromHeap32
  salloc = mod.salloc
  sallocCopy = mod.sallocCopy
  sallocBytes = mod.sallocBytes
  sallocArray = mod.sallocArray
  saveArray = mod.saveArray
  callSetter = mod.callSetter
  callGetter = mod.callGetter
  callGetter2 = mod.callGetter2
  callOp1 = mod.callOp1
  callOp2 = mod.callOp2
  callShare = mod.callShare
  callRecover = mod.callRecover
  callSetInput = mod.callSetInput
  callGetStr = mod.callGetStr
  callDeserialize = mod.callDeserialize
  callSerialize = mod.callSerialize

  initializedCurveType = curveType
  addWrappedMethods()

  const r: number = mod._mclBn_init(curveType, MCLBN_COMPILED_TIME_VAR)
  if (r !== 0) throw new Error(`_mclBn_init err ${r}`)
}
