name: test
on: [push]

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: node
      uses: actions/setup-node@v4
      with:
        node-version: "20"
    - run: npm install -D @types/node
    - run: npm test
    - run: npm run test-ts

